### ISSUE TITLE
failed to load source for dependency `obce`

### ISSUE THREAD

**Issue by TomaszWaszczyk** [paritytech/substrate-contracts-node#167]
While trying to compile the node I got:

```
    Updating git repository `https://github.com/727-Ventures/obce`
error: failed to compile `contracts-node v0.23.0 (https://github.com/paritytech/substrate-contracts-node.git#87a3d76c)`, intermediate artifacts can be found at `/tmp/cargo-installEfgqLE`

Caused by:
  failed to get `obce` as a dependency of package `pallet-assets-chain-extension v0.1.1 (https://github.com/727-Ventures/pallet-assets-chain-extension?branch=polkadot-v0.9.34#1680c99e)`
      ... which satisfies git dependency `pallet-assets-chain-extension` of package `contracts-node-runtime v0.23.0 (/home/tomek/.cargo/git/checkouts/substrate-contracts-node-cf7c16677784d274/87a3d76/runtime)`
      ... which satisfies path dependency `contracts-node-runtime` of package `contracts-node v0.23.0 (/home/tomek/.cargo/git/checkouts/substrate-contracts-node-cf7c16677784d274/87a3d76/node)`

Caused by:
  failed to load source for dependency `obce`

Caused by:
  Unable to update https://github.com/727-Ventures/obce?branch=polkadot-v0.9.34

Caused by:
  failed to find branch `polkadot-v0.9.34`

Caused by:
  cannot locate remote-tracking branch 'origin/polkadot-v0.9.34'; class=Reference (4); code=NotFound (-3)
```

Appreciate any hints.

**Comment by SkymanOne** [comment]
Have you tried running?
```
cargo update
```

**Comment by TomaszWaszczyk** [comment]
Of course. Many, many times.

**Comment by architectspactreon** [comment]
Facing the same error. 
**Branch:** main
**Command:** cargo run --release -- --tmp

**Logs:**

`Updating git repository `https://github.com/727-Ventures/obce`
error: failed to get `obce` as a dependency of package `pallet-assets-chain-extension v0.1.1 (https://github.com/727-Ventures/pallet-assets-chain-extension?branch=polkadot-v0.9.34#1680c99e)`
    ... which satisfies git dependency `pallet-assets-chain-extension` (locked to 0.1.1) of package `contracts-node-runtime v0.23.0 (/home/dev/Desktop/projects/dandelion/substrate-contracts-node/runtime)`
    ... which satisfies path dependency `contracts-node-runtime` (locked to 0.23.0) of package `contracts-node v0.23.0 (/home/dev/Desktop/projects/dandelion/substrate-contracts-node/node)`

Caused by:
  failed to load source for dependency `obce`

Caused by:
  Unable to update https://github.com/727-Ventures/obce?branch=polkadot-v0.9.34#bd369b13

Caused by:
  object not found - no match for id (bd369b13c7ab86590637cbd79e6ae0d70e67ea24); class=Odb (9); code=NotFound (-3)`

**Comment by TomaszWaszczyk** [comment]
This error was due to a missing branch in the `obce` repository.

Those who has the issue, try one more time, should work now.
